### ISSUE TITLE
Write a proper README

### ISSUE THREAD

**Issue by christophetd** [turingwars/turingwars#1]
- [x] Description
- [x] Screenshots / demo GIF
- [x] Examples
- [ ] Assembly documentation

**Comment by lbarman** [comment]
Started in 56bf6bbd1a40d3f7571759ef774b6ab699dbce95.

I'm not clear on the development process, e.g. in `web/` there are litteraly 8 `npm` commands:
```
    "start": "npm run build:views && ts-node src/server/main.ts",
    "test": "tslint -p . && jest",
    "test:watch": "jest --watch",
    "dev:frontend": "webpack-dev-server",
    "build:frontend": "webpack",
    "watch:frontend": "webpack --watch",
    "build:views": "topside --outDir src/server/views --baseDir src/server/templates src/server/templates/**/*.top.html",
    "gen:example": "ts-node"
```
This should be cleaned up and explained in the readme perhaps
