### ISSUE TITLE
Ranking system

### ISSUE THREAD

**Issue by hmil** [turingwars/turingwars#27]
I don't want to bother with logins and user accounts, this is way overkill. A low-cost, yet exciting way we can create engagement is by ranking the heros among themselves.

Building on top of #18 , submitted heros could be ranked. Then you have a stake in the game if you use recognizable tags in your hero's names,
such as `xXx.wutang.xXx Crusher v2.3` or `ℜℴℊ℧ℯ exterminator 1.0`. Basically, you get to tag the top of the list with your name if you make a killer program!

How to do the ranking system is an interesting problem. Assuming it is too expensive to simulate all heros against all other heros, how would we build a fair ranking system? How to make the system resilient to attacks? Example of attacks:
- I create a ton of stupid heros that jump to a given address, and then create a hero that hijacks that specific address, just so that its win/loss average stays high.
- I duplicate a top-performer hero a bunch of times, hoping that statistically, one of my copies will overthrow the rightful number 1.

cc @christophetd

**Comment by nicolasreich** [comment]
For the ranking, an elo rating could work I guess. 

To make the system resilient to some attacks it should be 
1. Impossible to make the same programs fight more than once (to prevent obvious boosting). This shouldn't be too hard to implement. 
2. Impossible to duplicate an existing program. This is harder as it requires some comparison of the programs. 

All in all I don't think we should bother too much about abuse yet. I'd be overjoyed if we get enough people playing our game to actually incentivise cheating.
