### ISSUE TITLE
UI sounds

### ISSUE THREAD

**Issue by hmil** [turingwars/turingwars#35]
TODO: Here be the list of sounds we want to add
- [x] Bleep when clicking a <Button> or selecting an element in the <HeroList>
- [x] Must-have: A mortal-combat style "Fight!" voice when the match starts

**Comment by lbarman** [comment]
For later use:
http://www.mortalkombatwarehouse.com/umk3/sounds/#hitsounds
http://soundfxcenter.com/download-sound/mortal-kombat-3-fight-sound-effect/
or rip from:
https://www.youtube.com/watch?v=0iUhFzgw-rY
