### ISSUE TITLE
CodeMirror enhancements

### ISSUE THREAD

**Issue by hmil** [turingwars/turingwars#43]
- [ ] Enable word-wrap
- [ ] Make the code window taller

**Comment by lbarman** [comment]
Code window taller done in https://github.com/turingwars/turingwars/pull/51
Word-wrap not done, how long are your lines ? :O

**Comment by hmil** [comment]
Comments tend to get really long to explain what a single instruction does. 
> jumps to the target instruction, the b-field contains a counter to track the number of times we have seen a mine and is edited a few instructions above by the scanning engine

**Comment by hmil** [comment]
Fuck line wrapping tho.
